/* === FILE: devices-data.js === */
/**
 * WebOS v0.8.2 Hardware Devices & Drivers Master Registry
 */
(function () {
  const INITIAL_DEVICES = [
    {
      id: "cpu",
      name: "Cyclone 1st Gen X9",
      category: "Processors",
      categoryIcon: "🖥️",
      manufacturer: "Cyclone Technologies",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "Cyclone WHQL Signature",
      critical: true,
      status: "working",
      installed: true,
      sizeMB: 125,
      location: "Socket AM4 - Bus 0, Dev 0, Func 0",
      hardwareId: "ACPI\\VEN_CYCL&DEV_00X9",
      powerState: "D0 (Fully Operational)",
      resources: { io: "0020-0021, 00A0-00A1", irq: "0, 8", mem: "FED00000-FED003FF" }
    },
    {
      id: "gpu",
      name: "Star R Pro",
      category: "Display Adapters",
      categoryIcon: "🎮",
      manufacturer: "Star Graphics",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "Star WHQL Signature",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 145,
      location: "PCI Express x16 (Bus 1, Dev 0, Func 0)",
      hardwareId: "PCI\\VEN_STAR&DEV_RPRO_01",
      powerState: "D0 (Fully Operational)",
      resources: { io: "03B0-03DF", irq: "16", mem: "E0000000-EFFFFFFF, F0000000-F01FFFFF" }
    },
    {
      id: "disk",
      name: "Bolt NV-64",
      category: "Disk Drives",
      categoryIcon: "💾",
      manufacturer: "Bolt Storage",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "Bolt WHQL Signature",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 85,
      location: "M.2 NVMe PCIe x4 Slot 1",
      hardwareId: "NVME\\VEN_BOLT&DEV_NV64_01",
      powerState: "D0 (Active Read/Write)",
      resources: { io: "N/A (Memory Mapped)", irq: "19", mem: "FE800000-FE803FFF" }
    },
    {
      id: "ram",
      name: "Black U5000 (8GB DDR4)",
      category: "Memory",
      categoryIcon: "🧠",
      manufacturer: "Black Memory",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "WebOS Core System",
      critical: true,
      status: "working",
      installed: true,
      sizeMB: 35,
      location: "DIMM Slot 1 & 2 (Dual Channel)",
      hardwareId: "MEM\\VEN_BLCK&DEV_U5000",
      powerState: "D0 (Self-Refresh Active)",
      resources: { io: "0080-008F", irq: "N/A", mem: "00000000-1FFFFFFF" }
    },
    {
      id: "audio",
      name: "woosh Audio HD",
      category: "Sound, Video & Game Controllers",
      categoryIcon: "🔊",
      manufacturer: "woosh Labs",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "woosh WHQL Signature",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 45,
      location: "HD Audio Bus 0, Dev 27, Func 0",
      hardwareId: "HDAUDIO\\VEN_WOOSH&DEV_HD01",
      powerState: "D0 (High Def Codec Active)",
      resources: { io: "0400-041F", irq: "22", mem: "FE700000-FE703FFF" }
    },
    {
      id: "wifi",
      name: "BoltLink Wi-Fi 5",
      category: "Network Adapters",
      categoryIcon: "🌐",
      manufacturer: "Bolt Networks",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "Bolt WHQL Signature",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 65,
      location: "PCI Express x1 (Bus 2, Dev 0, Func 0)",
      hardwareId: "PCI\\VEN_BOLT&DEV_WF5_01",
      powerState: "D0 (Radio Transceiver On)",
      resources: { io: "0500-053F", irq: "18", mem: "FE600000-FE601FFF" }
    },
    {
      id: "monitor",
      name: "markRED Retina Display",
      category: "Monitors",
      categoryIcon: "🖥️",
      manufacturer: "markRED Displays",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "markRED WHQL Signature",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 95,
      location: "Internal eDP Display Panel Port 0",
      hardwareId: "MONITOR\\MRK_RETINA15",
      powerState: "D0 (Panel Backlight 100%)",
      resources: { io: "N/A", irq: "N/A", mem: "D0000000-D0000FFF" }
    },
    {
      id: "battery",
      name: "highcell Power Cell",
      category: "Batteries",
      categoryIcon: "🔋",
      manufacturer: "highcell Energy",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "ACPI Control Signature",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 25,
      location: "Embedded Controller Battery 0",
      hardwareId: "ACPI\\PNP0C0A",
      powerState: "D0 (Discharging / AC Standby)",
      resources: { io: "0062, 0066", irq: "N/A", mem: "N/A" }
    },
    {
      id: "mouse",
      name: "OQ-9 Precision Mouse",
      category: "Mice & Pointing Devices",
      categoryIcon: "🖱️",
      manufacturer: "OQ Peripherals",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "HID Standard Signature",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 15,
      location: "USB Input Device (Port 1)",
      hardwareId: "HID\\VID_0Q09&PID_0001",
      powerState: "D0 (Optical Sensor Active)",
      resources: { io: "0060, 0064", irq: "12", mem: "N/A" }
    },
    {
      id: "keyboard",
      name: "KKW Keyboard",
      category: "Keyboards",
      categoryIcon: "⌨️",
      manufacturer: "KKW Devices",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "HID Standard Signature",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 18,
      location: "USB Input Device (Port 2)",
      hardwareId: "HID\\VID_KKW0&PID_0002",
      powerState: "D0 (Matrix Scanning Active)",
      resources: { io: "0060, 0064", irq: "1", mem: "N/A" }
    },
    {
      id: "usb",
      name: "fastF USB 3.0 Controller",
      category: "USB Controllers",
      categoryIcon: "🔌",
      manufacturer: "fastF Technologies",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "xHCI WHQL Signature",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 30,
      location: "PCI Bus 0, Dev 20, Func 0",
      hardwareId: "PCI\\VEN_FASTF&DEV_XHCI01",
      powerState: "D0 (Host Controller Ready)",
      resources: { io: "N/A", irq: "24", mem: "FE500000-FE50FFFF" }
    },
    {
      id: "cooler",
      name: "Cyclone Frost Cooler",
      category: "System Devices",
      categoryIcon: "⚡",
      manufacturer: "Cyclone Technologies",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "ACPI Fan Control",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 20,
      location: "Motherboard Fan Header 1",
      hardwareId: "ACPI\\CYCL_FAN01",
      powerState: "D0 (1850 RPM Dynamic)",
      resources: { io: "0290-0294", irq: "N/A", mem: "N/A" }
    },
    {
      id: "psu",
      name: "Volt 450W PSU",
      category: "System Devices",
      categoryIcon: "⚡",
      manufacturer: "Volt Power",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "PMBus Standard",
      critical: false,
      status: "working",
      installed: true,
      sizeMB: 22,
      location: "Internal ATX Power Unit",
      hardwareId: "PMBUS\\VOLT_450W",
      powerState: "D0 (Voltage Rail 12V / 5V / 3.3V)",
      resources: { io: "SMBus 0x58", irq: "N/A", mem: "N/A" }
    },
    {
      id: "motherboard",
      name: "Bolt B350-M Motherboard",
      category: "System Devices",
      categoryIcon: "⚡",
      manufacturer: "Bolt Systems",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "Bolt Core BIOS",
      critical: true,
      status: "working",
      installed: true,
      sizeMB: 75,
      location: "Main System Board Chassis",
      hardwareId: "ACPI\\BOLT_B350M_MAIN",
      powerState: "D0 (ACPI S0 State)",
      resources: { io: "0000-FFFF", irq: "0-31", mem: "00000000-FFFFFFFF" }
    },
    {
      id: "bootloader",
      name: "WebOS Boot Loader",
      category: "System Devices",
      categoryIcon: "⚡",
      manufacturer: "WebOS Foundation",
      driverVersion: "1.0.0.0",
      driverDate: "Aug 2026",
      signer: "WebOS UEFI CA",
      critical: true,
      status: "working",
      installed: true,
      sizeMB: 55,
      location: "UEFI Firmware NVRAM Block",
      hardwareId: "UEFI\\WEBOS_BOOTLOADER",
      powerState: "D0 (Kernel Stage Active)",
      resources: { io: "N/A", irq: "N/A", mem: "FFF00000-FFFFFFFF" }
    }
  ];

  // Live session clone
  let devices = JSON.parse(JSON.stringify(INITIAL_DEVICES));

  window.devicesData = {
    getAll: () => devices,
    getDevice: (id) => devices.find((d) => d.id === id),
    updateDevice: (id, updates) => {
      const dev = devices.find((d) => d.id === id);
      if (dev) Object.assign(dev, updates);
      return dev;
    },
    resetAll: () => {
      devices = JSON.parse(JSON.stringify(INITIAL_DEVICES));
    }
  };
})();
