/* === FILE: store-data.js === */
/**
 * WebOS v0.7 App Store Catalog Data (9 Apps)
 */
(function () {
  window.storeApps = [
    { id: "weather", name: "Weather", icon: "🌤️", category: "Utilities", price: 0, description: "Real-time weather conditions, forecasts, and trends.", longDescription: "Stay informed with dynamic high-accuracy simulated forecasting.", rating: 4.5, downloads: "120k+", sizeMB: 45, size: "45 MB", ageRating: "4+", developer: "WebOS Weather Team", isInstalled: false },
    { id: "terminal", name: "Terminal", icon: "💻", category: "Utilities", price: 0, description: "UNIX-inspired command line interface for power users.", longDescription: "Execute shell commands, view system stats, and run neofetch.", rating: 4.8, downloads: "85k+", sizeMB: 32, size: "32 MB", ageRating: "12+", developer: "WebOS Tools", isInstalled: false },
    { id: "music", name: "Music Player", icon: "🎵", category: "Entertainment", price: 0, description: "Personal audio player with playlists and playback controls.", longDescription: "Enjoy audio tracks, custom playlists, volume controls, and animations.", rating: 4.3, downloads: "200k+", sizeMB: 180, size: "180 MB", ageRating: "4+", developer: "WebOS Media", isInstalled: false },
    { id: "paint", name: "Paint", icon: "🎨", category: "Entertainment", price: 0, description: "Draw and design with color palettes and brush tools.", longDescription: "Canvas-based illustration suite with custom brushes and palette controls.", rating: 4.6, downloads: "150k+", sizeMB: 95, size: "95 MB", ageRating: "4+", developer: "WebOS Creative", isInstalled: false },
    { id: "clock", name: "Clock", icon: "🕐", category: "Utilities", price: 0, description: "Global world clocks across major timezones.", longDescription: "Track local time alongside UTC, New York, and Tokyo financial markets.", rating: 4.4, downloads: "90k+", sizeMB: 28, size: "28 MB", ageRating: "4+", developer: "WebOS Utilities", isInstalled: false },
    { id: "calendar", name: "Calendar", icon: "📅", category: "Productivity", price: 0, description: "Monthly planner with persistent event scheduling.", longDescription: "Full interactive monthly calendar grid with local storage sync.", rating: 4.7, downloads: "175k+", sizeMB: 67, size: "67 MB", ageRating: "4+", developer: "WebOS Productivity", isInstalled: false },
    { id: "gamecenter", name: "Game Center", icon: "🎮", category: "Entertainment", price: 4.99, description: "Ultimate gaming hub with achievements and leaderboards.", longDescription: "View achievements, global leaderboards, game stats, and upcoming titles.", rating: 4.7, downloads: "50k+", sizeMB: 1200, size: "1.2 GB", ageRating: "12+", developer: "WebOS Gaming", isInstalled: false },
    { id: "videoeditor", name: "Video Editor", icon: "🎬", category: "Productivity", price: 9.99, description: "Professional video editing with multi-track timeline.", longDescription: "Timeline clip controls, video transitions, trimming tools, and preview window.", rating: 4.1, downloads: "30k+", sizeMB: 2100, size: "2.1 GB", ageRating: "4+", developer: "WebOS Creative", isInstalled: false },
    { id: "wallpapers", name: "Wallpapers PCS", icon: "🖼️", category: "Entertainment", price: 0, description: "Beautiful wallpapers for your desktop. Browse 10 stunning designs with free and pro tiers.", longDescription: "Wallpapers PCS brings you a curated collection of 10 high-quality wallpapers ranging from 38MB to 100MB each.", rating: 4.5, downloads: "75k+", sizeMB: 500, size: "500 MB", ageRating: "4+", developer: "Papers For PC Inc.", isInstalled: false }
  ];
})();
