/* === FILE: store-data.js === */
/**
 * WebOS v0.6 App Store Data Definitions (10 Apps)
 */
(function () {
  window.storeApps = [
    {
      id: "weather",
      name: "Weather",
      icon: "🌤️",
      category: "Utilities",
      price: 0,
      description: "Real-time weather at your fingertips. Temperature, conditions, and 3-day forecast.",
      longDescription: "Stay ahead of the elements with Weather for WebOS. Features dynamic conditions, hourly trends, and high-accuracy simulated forecasting.",
      rating: 4.5,
      downloads: "120k+",
      size: "12 MB",
      ageRating: "4+",
      developer: "WebOS Weather Team",
      isInstalled: false
    },
    {
      id: "terminal",
      name: "Terminal",
      icon: "💻",
      category: "Utilities",
      price: 0,
      description: "Command-line interface for power users. Execute commands like ls, echo, neofetch, and more.",
      longDescription: "A powerful UNIX-inspired shell emulator inside WebOS. Includes command history, custom neofetch system info, and Mbank integration.",
      rating: 4.8,
      downloads: "85k+",
      size: "8 MB",
      ageRating: "12+",
      developer: "WebOS Tools",
      isInstalled: false
    },
    {
      id: "music",
      name: "Music Player",
      icon: "🎵",
      category: "Entertainment",
      price: 0,
      description: "Your personal music companion. Playlist management, progress bar, volume control.",
      longDescription: "Enjoy your favorite audio tracks with interactive playback controls, animated progress bar, volume adjustment, and custom playlist support.",
      rating: 4.3,
      downloads: "200k+",
      size: "22 MB",
      ageRating: "4+",
      developer: "WebOS Media",
      isInstalled: false
    },
    {
      id: "paint",
      name: "Paint",
      icon: "🎨",
      category: "Entertainment",
      price: 0,
      description: "Unleash your creativity. Draw with multiple colors and brush sizes on a blank canvas.",
      longDescription: "Canvas-based drawing tool. Express yourself with custom brush sizes, a full color spectrum palette, and instant canvas clearing.",
      rating: 4.6,
      downloads: "150k+",
      size: "15 MB",
      ageRating: "4+",
      developer: "WebOS Creative",
      isInstalled: false
    },
    {
      id: "clock",
      name: "Clock",
      icon: "🕐",
      category: "Utilities",
      price: 0,
      description: "Track time across the world. View local, UTC, New York, and Tokyo timezones.",
      longDescription: "A real-time global clock utility displaying local time alongside major world financial centers (UTC, New York, Tokyo).",
      rating: 4.4,
      downloads: "90k+",
      size: "6 MB",
      ageRating: "4+",
      developer: "WebOS Utilities",
      isInstalled: false
    },
    {
      id: "browser",
      name: "Browser",
      icon: "🌐",
      category: "Utilities",
      price: 0,
      description: "Browse the web. Navigate between pages with address bar and back/forward buttons.",
      longDescription: "Lightweight browser shell featuring address bar navigation, history stack (back/forward), and built-in web pages.",
      rating: 4.2,
      downloads: "300k+",
      size: "18 MB",
      ageRating: "12+",
      developer: "WebOS Internet",
      isInstalled: false
    },
    {
      id: "calendar",
      name: "Calendar",
      icon: "📅",
      category: "Productivity",
      price: 0,
      description: "Stay organized. Monthly calendar with event creation and localStorage persistence.",
      longDescription: "Full monthly interactive calendar grid. Add, store, and view persistent events on any date with local storage synchronization.",
      rating: 4.7,
      downloads: "175k+",
      size: "10 MB",
      ageRating: "4+",
      developer: "WebOS Productivity",
      isInstalled: false
    },
    {
      id: "mbank",
      name: "Mbank",
      icon: "🏦",
      category: "Finance",
      price: 0,
      description: "Your virtual wallet. Manage funds, view transactions, make purchases in the App Store.",
      longDescription: "Centralized virtual banking application. View your balance, top up virtual funds, and review real-time transaction logs.",
      rating: 4.9,
      downloads: "500k+",
      size: "25 MB",
      ageRating: "4+",
      developer: "WebOS Finance",
      isInstalled: true,
      preInstalled: true
    },
    {
      id: "gamecenter",
      name: "Game Center",
      icon: "🎮",
      category: "Entertainment",
      price: 4.99,
      description: "The ultimate gaming hub. Challenge friends, track achievements, discover new games.",
      longDescription: "Premium gaming platform suite for WebOS. View player achievements, global leaderboards, game stats, and upcoming releases.",
      rating: 4.7,
      downloads: "50k+",
      size: "45 MB",
      ageRating: "12+",
      developer: "WebOS Gaming",
      isInstalled: false
    },
    {
      id: "videoeditor",
      name: "Video Editor",
      icon: "🎬",
      category: "Productivity",
      price: 9.99,
      description: "Professional video editing tools. Trim, cut, add effects and transitions.",
      longDescription: "Advanced suite for video editing. Timeline track controls, clip trimming, split tools, and real-time playback preview window.",
      rating: 4.1,
      downloads: "30k+",
      size: "95 MB",
      ageRating: "4+",
      developer: "WebOS Creative",
      isInstalled: false
    }
  ];
})();
